# Generated by Django 5.2.9 on 2026-05-21 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Attendance date')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], max_length=10)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='course.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-date', 'student__name'],
                'indexes': [models.Index(fields=['course', 'date'], name='attendance__course__abd009_idx'), models.Index(fields=['student', 'course'], name='attendance__student_e4c8ff_idx'), models.Index(fields=['status'], name='attendance__status_132c06_idx'), models.Index(fields=['date'], name='attendance__date_61f2e1_idx')],
                'unique_together': {('student', 'course', 'date')},
            },
        ),
    ]
