# Generated by Django 5.2.9 on 2026-05-22 18:39

import apps.billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='year',
            field=models.PositiveIntegerField(default=apps.billing.models.current_year),
        ),
    ]
