# Generated by Django 5.2.9 on 2026-05-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('school_name', models.CharField(default='EquiManage Riding School', max_length=255)),
                ('contact_email', models.EmailField(default='contact@equimanage.com', max_length=254)),
                ('contact_phone', models.CharField(default='+92 300 1234567', max_length=50)),
                ('tax_vat_id', models.CharField(blank=True, default='', max_length=50)),
                ('business_address', models.TextField(default='123 Riding Club Road, Lahore, Pakistan')),
                ('smtp_host', models.CharField(default='smtp.gmail.com', max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_password', models.CharField(blank=True, default='', max_length=255)),
                ('default_from_email', models.EmailField(default='noreply@equimanage.com', max_length=254)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
