# Generated by Django 5.2.9 on 2026-05-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('duration_months', models.PositiveIntegerField(help_text='Duration in months')),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('class_time', models.TimeField()),
                ('class_days', models.JSONField(default=list, help_text="List of weekdays e.g. ['Monday', 'Wednesday']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
