# Generated by Django 5.2.9 on 2026-05-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horse',
            name='breed',
            field=models.CharField(choices=[('Arabian', 'Arabian'), ('Thoroughbred', 'Thoroughbred'), ('Mustang', 'Mustang'), ('Friesian', 'Friesian'), ('Quarter Horse', 'Quarter Horse'), ('Mixed Breed', 'Mixed Breed')], max_length=100),
        ),
    ]
