# Generated by Django 5.2.9 on 2026-05-22 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse', '0002_alter_horse_breed'),
    ]

    operations = [
        migrations.AddField(
            model_name='horseowner',
            name='owner_type',
            field=models.CharField(choices=[('Horse Care', 'Horse Care'), ('Horse Training', 'Horse Training'), ('Company Owned', 'Company Owned')], default='Horse Care', max_length=50),
        ),
    ]
